# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-18 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('preference', models.IntegerField()),
                ('Livecast', models.BooleanField()),
                ('sub', models.IntegerField()),
                ('linkone', models.TextField()),
                ('linktwo', models.TextField()),
                ('linkthree', models.TextField()),
            ],
        ),
    ]
