# Generated by Django 3.0.6 on 2020-06-29 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='photo',
            name='pic',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
