# Generated by Django 3.0.6 on 2020-07-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20200629_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
