# Generated by Django 3.0.6 on 2020-07-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20200706_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='pic',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
